name: Compile IPK Package

on:
  push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]
  watch:
    types: started
  #schedule:
    #- cron:  '0 0 28-31 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id
    
    env:
      URL: https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz #需要修改

    
    steps:

    - name: Install dependencies
      run: |
       # https://openwrt.org/docs/guide-developer/build-system/install-buildsystem
        sudo -E apt-get -qq update
        sudo -E apt-get -y install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        
    - name: Install UPX
      run: |
        cd /tmp
        latest_version=$(wget -qO- https://api.github.com/repos/upx/upx/releases/latest | grep 'tag_name' | c
